# this program displays the stages of hangman

print('Hey there, what is your name?')
name=input()

print('Hey,'+name) 
print('The hangman game is under construction, maybe you’ll get to play it in a few weeks…')

print('This is what various stages of hangman game will look like…')

print('Stage 0') 

print('|__________ '  )                      
print('|/         |') 
print('|    ')  
print('|') 
print('|   ')   
print('|') 
print('|   ')                             
print('-------------')      

print('stage 1')
print('|__________ '  )                      
print('|/         |') 
print('|          0')  
print('|           ' )
print('           ')
print('|         ' )  
print('|') 
print('|   ')                             
print('-------------')

print('stage 2')
print('|__________ '  )                      
print('|/         |') 
print('|          0')  
print('|          | ' )
print('           ')
print('|           ' )  
print('|') 
print('|   ')                             
print('-------------')

print('stage 3')
print('|__________ '  )                      
print('|/         |') 
print('|          0')  
print('|         /|  ' )
print('|           ' )  
print('|') 
print('|   ')                             
print('-------------')

print('stage 4')
print('|__________ '  )                      
print('|/         |') 
print('|          0')  
print('|         /|\  ' )
print('|           ' )  
print('|') 
print('|   ')                             
print('-------------')

print('stage 5')
print('|__________ '  )                      
print('|/         |') 
print('|          0')  
print('|         /|\  ' )
print('|         /   ' )  
print('|') 
print('|   ')                             
print('-------------')

print('stage 6')



print('|__________ '  )                      
print('|/         |') 
print('|          0')  
print('|         /|\  ' )
print('|         / \  ' )  
print('|') 
print('|   ')                             
print('-------------') 